### ISSUE TITLE
Portfolio Project - Live Version

### ISSUE THREAD

**Issue by Rysth** [Rysth/Portfolio-Project#10]
### 🏅 Main Features  
_Project Requirements -> https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md_

List of things that were implemented based on the requirements:

- ✅ Deployed the Live Version of my project using Github Pages.
- ✅ Created a Github Issue because already was deployed.

**_Live Version_**-> https://rysth.github.io/Portfolio-Project/

_John Palacios_
_Microverse Student_

**Comment by Ofarouq310** [comment]
Hi @Rysth, ✋ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://github.com/kambereBr/Portfolio/assets/102612396/c231b103-6dcb-45fc-b5cb-89156d66bb61)

## Highlights
✅ Live demo link works as expected.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
