### ISSUE TITLE
Peer Review - Mahammad

### ISSUE THREAD

**Issue by mahammad-mostafa** [Rysth/Portfolio-Project#9]
## 🖊️ Feedback

🥇 Good desktop responsive design
🥇 Excellent usage of css variables
🥇 Very close template implementation

## 💡 Suggestions

✅ Define a default font size of `16px` for `rem` unit values
✅ Use of common container for all sections and content
✅ Menu section should be fixed while scrolling the page
✅ Contact form needs to remove the outline effect when selected
✅ Name and email input needs to use `autocomplete` attribute
✅ Background in `main` tag should be within the head line section

**Comment by Rysth** [comment]
Thanks, @mahammad-mostafa! All to all the other Teammates.

## Suggestions Implemented 💯 

✅ Added a `font-size: 16px` attribute to the Body selector on the CSS file.
✅ Fixed the `container` class to work correctly on each section.
✅ Fixed the position of the `header` to make him attached to the top of the screen.
✅ Applied the `outline: none` to each `input` within the Form Element on the Contacts Section.
✅ Added the `autocomplete="on"` on the `form` tag.
✅ Attached is the Background image of his respective container in the Headline Section.
